"""Data models used across the AI controller application."""
from __future__ import annotations

from dataclasses import dataclass, field, asdict
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional


class ResponseMode(Enum):
    """AI response modes."""

    JSON = "json"


@dataclass
class ThinkingConfig:
    """Represents thinking configuration for the AI model."""

    thinking_budget: int = -1


@dataclass
class FileOutput:
    """Structure describing a single file generated by the AI."""

    filename: str
    filetype: str
    code: str
    opens_window: bool = False
    window_title: Optional[str] = None
    install_requirements: Optional[List[str]] = None
    dependencies: Optional[List[str]] = None
    description: Optional[str] = None
    run_command: Optional[str] = None
    is_web_app: bool = False
    can_open_standalone: bool = False
    server_address: Optional[str] = None
    web_title: Optional[str] = None
    file_operation: Optional[str] = None


@dataclass
class ProjectOutput:
    """Full project output returned by the AI."""

    project_name: str
    description: str
    files: List[FileOutput]
    main_file: Optional[str] = None
    setup_instructions: Optional[List[str]] = None
    run_instructions: Optional[List[str]] = None


@dataclass
class AIConfig:
    """Configuration persisted for connecting to Gemini."""

    connection_method: str = "api_key"
    gemini_api_key: str = ""
    model_name: str = "gemini-2.5-pro"
    system_instruction: str = ""
    prompt_mode: str = "default"
    generation_params: Dict[str, Any] | None = None
    thinking_config: Dict[str, Any] | None = None
    safety_settings: Dict[str, str] | None = None
    automation_settings: Dict[str, Any] | None = None

    def __post_init__(self) -> None:
        if self.generation_params is None:
            self.generation_params = {
                "temperature": 0.7,
                "top_p": 0.95,
                "top_k": 64,
                "max_output_tokens": 8192,
                "candidate_count": 1,
                "stop_sequences": [],
                "response_mime_type": "application/json",
            }
        if self.thinking_config is None:
            self.thinking_config = {"thinking_budget": -1}
        if self.safety_settings is None:
            self.safety_settings = {
                "HARM_CATEGORY_HARASSMENT": "BLOCK_MEDIUM_AND_ABOVE",
                "HARM_CATEGORY_HATE_SPEECH": "BLOCK_MEDIUM_AND_ABOVE",
                "HARM_CATEGORY_SEXUALLY_EXPLICIT": "BLOCK_MEDIUM_AND_ABOVE",
                "HARM_CATEGORY_DANGEROUS_CONTENT": "BLOCK_MEDIUM_AND_ABOVE",
            }
        if self.automation_settings is None:
            self.automation_settings = {
                "auto_error_fix": False,
                "auto_optimize": False,
                "auto_test": False,
                "monitor_interval": 5,
            }

        if not self.prompt_mode:
            self.prompt_mode = "default"
        else:
            self.prompt_mode = str(self.prompt_mode).lower()
            if self.prompt_mode not in {"default", "creative"}:
                self.prompt_mode = "default"


@dataclass
class ConversationMessage:
    """Represents a single conversation message."""

    role: str
    content: str
    timestamp: str
    files: Optional[List[Dict]] = None
    metadata: Optional[Dict] = None
    terminal_output: Optional[str] = None
    usage_metadata: Optional[Dict] = None


@dataclass
class ProjectConversation:
    """Conversation history for a project."""

    project_dir: str
    project_name: str
    messages: List[ConversationMessage] = field(default_factory=list)
    created_at: str = ""
    updated_at: str = ""
    memory_snapshot: Dict[str, Any] = field(default_factory=dict)
    evaluation_snapshot: Dict[str, Any] = field(default_factory=dict)
    accumulated_long_term_memory: List[str] = field(default_factory=list)


@dataclass
class ProcessResult:
    """Structured result of executing an AI instruction."""

    success: bool
    output: str = ""
    files_created: List[str] = field(default_factory=list)
    files_updated: List[str] = field(default_factory=list)
    project_data: Optional[ProjectOutput] = None
    ai_response: str = ""
    ai_response_json: Optional[Dict] = None
    installation_logs: List[str] = field(default_factory=list)
    error: str = ""
    screenshots: List[str] = field(default_factory=list)
    is_iteration: bool = False
    usage_metadata: Optional[Dict] = None
    terminal_output: str = ""
    memory_snapshot: Optional[Dict[str, Any]] = None
    evaluation_snapshot: Optional[Dict[str, Any]] = None
    diagnostics_report: List[Dict[str, Any]] = field(default_factory=list)
    error_report_path: Optional[str] = None


__all__ = [
    "ResponseMode",
    "ThinkingConfig",
    "FileOutput",
    "ProjectOutput",
    "AIConfig",
    "ConversationMessage",
    "ProjectConversation",
    "ProcessResult",
    "asdict",
    "Path",
]
